<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/user/_show.blade.php" was generated by ProBot AI.
* Date: 16/05/2023 12:54:04 PM
* Contact: towhid1@outlook.com
*/
?>

<?php $__env->startSection('title','Show User'); ?>
<?php $__env->startSection('style'); ?>


<?php $__env->stopSection(); ?>
<?php $__env->startSection('page'); ?>
<a class='btn btn-success' href="<?php echo e(route('users.index')); ?>">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td><?php echo e($user->id); ?></td></tr>
		<tr><th>Username</th><td><?php echo e($user->username); ?></td></tr>
		<tr><th>Email</th><td><?php echo e($user->email); ?></td></tr>
		<tr><th>Password</th><td><?php echo e($user->password); ?></td></tr>
		<tr><th>Created At</th><td><?php echo e($user->created_at); ?></td></tr>
		<tr><th>Updated At</th><td><?php echo e($user->updated_at); ?></td></tr>

</tbody>
</table>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('script'); ?>


<?php $__env->stopSection(); ?>

<?php echo $__env->make('layout.erp.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\innova-project\resources\views/pages/erp/user/show.blade.php ENDPATH**/ ?>