<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/user/_index.blade.php" was generated by ProBot AI.
* Date: 16/05/2023 12:54:04 PM
* Contact: towhid1@outlook.com
*/
?>

<?php $__env->startSection('title','Manage User'); ?>
<?php $__env->startSection('style'); ?>


<?php $__env->stopSection(); ?>
<?php $__env->startSection('page'); ?>
<a href="<?php echo e(route('users.create')); ?>">New User</a>
<table class="table table-hover text-nowrap">
	<thead>
		<tr>
			<th>Id</th>
			<th>Username</th>
			<th>Email</th>
			<th>Password</th>
			<th>Created At</th>
			<th>Updated At</th>

			<th>Action</th>
		</tr>
	</thead>
	<tbody>
	<?php $__currentLoopData = $users; $__env->addLoop($__currentLoopData); foreach($__currentLoopData as $user): $__env->incrementLoopIndices(); $loop = $__env->getLastLoop(); ?>
		<tr>
			<td><?php echo e($user->id); ?></td>
			<td><?php echo e($user->username); ?></td>
			<td><?php echo e($user->email); ?></td>
			<td><?php echo e($user->password); ?></td>
			<td><?php echo e($user->created_at); ?></td>
			<td><?php echo e($user->updated_at); ?></td>

			<td>
			<form action = "<?php echo e(route('users.destroy',$user->id)); ?>" method = "post">
				<a class= 'btn btn-primary' href = "<?php echo e(route('users.show',$user->id)); ?>">View</a>
				<a class= 'btn btn-success' href = "<?php echo e(route('users.edit',$user->id)); ?>"> Edit </a>
				<?php echo method_field('DELETE'); ?>
				<?php echo csrf_field(); ?>
				<input type = "submit" class="btn btn-danger" name = "delete" value = "Delete" />
			</form>
			</td>
		</tr>
	<?php endforeach; $__env->popLoop(); $loop = $__env->getLastLoop(); ?>
	</tbody>
</table>
<?php $__env->stopSection(); ?>
<?php $__env->startSection('script'); ?>


<?php $__env->stopSection(); ?>

<?php echo $__env->make('layout.erp.app', \Illuminate\Support\Arr::except(get_defined_vars(), ['__data', '__path']))->render(); ?><?php /**PATH C:\xampp\htdocs\innova-project\resources\views/pages/erp/user/index.blade.php ENDPATH**/ ?>