<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "resources/views/user/_show.blade.php" was generated by ProBot AI.
* Date: 16/05/2023 12:54:04 PM
* Contact: towhid1@outlook.com
*/
?>
@extends('layout.erp.app')
@section('title','Show User')
@section('style')


@endsection
@section('page')
<a class='btn btn-success' href="{{route('users.index')}}">Manage</a>
<table class='table table-striped text-nowrap'>
<tbody>
		<tr><th>Id</th><td>{{$user->id}}</td></tr>
		<tr><th>Username</th><td>{{$user->username}}</td></tr>
		<tr><th>Email</th><td>{{$user->email}}</td></tr>
		<tr><th>Password</th><td>{{$user->password}}</td></tr>
		<tr><th>Created At</th><td>{{$user->created_at}}</td></tr>
		<tr><th>Updated At</th><td>{{$user->updated_at}}</td></tr>

</tbody>
</table>
@endsection
@section('script')


@endsection
