<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_PhotoController.php" was generated by ProBot AI.
* Date: 16/05/2023 12:46:27 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Photo;
use App\Models\Post;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class PhotoController extends Controller{
	public function index(){
		$photos = Photo::paginate(10);
		return view("pages.erp.photo.index",["photos"=>$photos]);
	}
	public function create(){
		return view("pages.erp.photo.create",["posts"=>Post::all()]);
	}
	public function store(Request $request){
		//Photo::create($request->all());
		$photo = new Photo;
		$photo->name=$request->name;
		$photo->post_id=$request->post_id;
date_default_timezone_set("Asia/Dhaka");
		$photo->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$photo->updated_at=date('Y-m-d H:i:s');

		$photo->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$photo = Photo::find($id);
		return view("pages.erp.photo.show",["photo"=>$photo]);
	}
	public function edit(Photo $photo){
		return view("pages.erp.photo.edit",["photo"=>$photo,"posts"=>Post::all()]);
	}
	public function update(Request $request,Photo $photo){
		//Photo::update($request->all());
		$photo = Photo::find($photo->id);
		$photo->name=$request->name;
		$photo->post_id=$request->post_id;
date_default_timezone_set("Asia/Dhaka");
		$photo->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$photo->updated_at=date('Y-m-d H:i:s');

		$photo->save();

		return redirect()->route("photos.index")->with('success','Updated Successfully.');
	}
	public function destroy(Photo $photo){
		$photo->delete();
		return redirect()->route("photos.index")->with('success', 'Deleted Successfully.');
	}
}
?>
