<?php
/*
* ProBot Version: 3.0
* Laravel Version: 10x
* Description: This source file "app/Http/_ReactionController.php" was generated by ProBot AI.
* Date: 16/05/2023 12:48:17 PM
* Contact: towhid1@outlook.com
*/
namespace App\Http\Controllers;
use App\Http\Controllers\Controller;
use App\Models\Reaction;
use App\Models\User;
use App\Models\Comment;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Redirect;
use Illuminate\Support\Facades\DB;
use Illuminate\Pagination\Paginator;
class ReactionController extends Controller{
	public function index(){
		$reactions = Reaction::paginate(10);
		return view("pages.erp.reaction.index",["reactions"=>$reactions]);
	}
	public function create(){
		return view("pages.erp.reaction.create",["users"=>User::all(),"comments"=>Comment::all()]);
	}
	public function store(Request $request){
		//Reaction::create($request->all());
		$reaction = new Reaction;
		$reaction->reaction_type=$request->reaction_type;
		$reaction->user_id=$request->user_id;
		$reaction->comment_id=$request->comment_id;
date_default_timezone_set("Asia/Dhaka");
		$reaction->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$reaction->updated_at=date('Y-m-d H:i:s');

		$reaction->save();

		return back()->with('success', 'Created Successfully.');
	}
	public function show($id){
		$reaction = Reaction::find($id);
		return view("pages.erp.reaction.show",["reaction"=>$reaction]);
	}
	public function edit(Reaction $reaction){
		return view("pages.erp.reaction.edit",["reaction"=>$reaction,"users"=>User::all(),"comments"=>Comment::all()]);
	}
	public function update(Request $request,Reaction $reaction){
		//Reaction::update($request->all());
		$reaction = Reaction::find($reaction->id);
		$reaction->reaction_type=$request->reaction_type;
		$reaction->user_id=$request->user_id;
		$reaction->comment_id=$request->comment_id;
date_default_timezone_set("Asia/Dhaka");
		$reaction->created_at=date('Y-m-d H:i:s');
date_default_timezone_set("Asia/Dhaka");
		$reaction->updated_at=date('Y-m-d H:i:s');

		$reaction->save();

		return redirect()->route("reactions.index")->with('success','Updated Successfully.');
	}
	public function destroy(Reaction $reaction){
		$reaction->delete();
		return redirect()->route("reactions.index")->with('success', 'Deleted Successfully.');
	}
}
?>
